### ISSUE TITLE
Broken submodule

### ISSUE THREAD

**Issue by matuszeg** [datastax/php-dse-driver#1]
Your submodule git@github.com:riptano/cpp-driver-dse.git is not publicly available, which breaks this repo. I changed it to git@github.com:datastax/cpp-driver-dse.git or https://github.com/datastax/cpp-driver-dse which fixed the problem for me. Either the url needs to change or the repo was made private mistakenly. but this is causing an issue with this source.

**Comment by mikefero** [comment]
Thank you for bringing this to our attention. This will be corrected in the next PHP DSE driver release.
